version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - ./src:/web/src
    ports:
      - "3000:8080"
    command: npm start
  worker:
    build:
      context: .
      dockerfile: Dockerfile.eddn
    volumes:
      - ./src:/web/src
    command: npm run start:worker
