version: "2"
services:
  web:
    build: .
    volumes:
      - ./src:/web/src
    ports:
      - "3000:8080"
    command: npm start
  worker:
    build:
      context: ./node_modules/node-eddn-listener/
    command: npm run start
